//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"adm_role_info")]
    public partial class ADM_ROLE_INFO : XPLiteObject
    {
        int fROLE_ID;
        [Key(true)]
        [Persistent(@"role_id")]
        public int ROLE_ID
        {
            get { return fROLE_ID; }
            set { SetPropertyValue<int>(nameof(ROLE_ID), ref fROLE_ID, value); }
        }
        int? fAPP_ID;
        [Persistent(@"app_id")]
        [ColumnDbDefaultValue("'-1'::integer")]
        public int? APP_ID
        {
            get { return fAPP_ID; }
            set { SetPropertyValue<int?>(nameof(APP_ID), ref fAPP_ID, value); }
        }
        string fROLE_CODE;
        [Size(50)]
        [Persistent(@"role_code")]
        public string ROLE_CODE
        {
            get { return fROLE_CODE; }
            set { SetPropertyValue<string>(nameof(ROLE_CODE), ref fROLE_CODE, value); }
        }
        string fROLE_NAME;
        [Size(255)]
        [Persistent(@"role_name")]
        public string ROLE_NAME
        {
            get { return fROLE_NAME; }
            set { SetPropertyValue<string>(nameof(ROLE_NAME), ref fROLE_NAME, value); }
        }
        int fORG_LV;
        [Persistent(@"org_lv")]
        public int ORG_LV
        {
            get { return fORG_LV; }
            set { SetPropertyValue<int>(nameof(ORG_LV), ref fORG_LV, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        [ColumnDbDefaultValue("'a'::bpchar")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        [ColumnDbDefaultValue("'n'::bpchar")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        int fREF_ID;
        [Persistent(@"ref_id")]
        public int REF_ID
        {
            get { return fREF_ID; }
            set { SetPropertyValue<int>(nameof(REF_ID), ref fREF_ID, value); }
        }
        string fREF_UNIQUE;
        [Size(17)]
        [Persistent(@"ref_unique")]
        public string REF_UNIQUE
        {
            get { return fREF_UNIQUE; }
            set { SetPropertyValue<string>(nameof(REF_UNIQUE), ref fREF_UNIQUE, value); }
        }
        int fROLE_SEQ;
        [Persistent(@"role_seq")]
        public int ROLE_SEQ
        {
            get { return fROLE_SEQ; }
            set { SetPropertyValue<int>(nameof(ROLE_SEQ), ref fROLE_SEQ, value); }
        }
    }

}
