//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"adm_log")]
    public partial class ADM_LOG : XPLiteObject
    {
        int fLOG_ID;
        [Key(true)]
        [Persistent(@"log_id")]
        public int LOG_ID
        {
            get { return fLOG_ID; }
            set { SetPropertyValue<int>(nameof(LOG_ID), ref fLOG_ID, value); }
        }
        DateTime fLOG_DATE;
        [Persistent(@"log_date")]
        public DateTime LOG_DATE
        {
            get { return fLOG_DATE; }
            set { SetPropertyValue<DateTime>(nameof(LOG_DATE), ref fLOG_DATE, value); }
        }
        DateTime fEVENT_DATE;
        [Persistent(@"event_date")]
        public DateTime EVENT_DATE
        {
            get { return fEVENT_DATE; }
            set { SetPropertyValue<DateTime>(nameof(EVENT_DATE), ref fEVENT_DATE, value); }
        }
        string fEVENT_TYPE;
        [Size(50)]
        [Persistent(@"event_type")]
        public string EVENT_TYPE
        {
            get { return fEVENT_TYPE; }
            set { SetPropertyValue<string>(nameof(EVENT_TYPE), ref fEVENT_TYPE, value); }
        }
        string fSYSTEM_NAME;
        [Size(50)]
        [Persistent(@"system_name")]
        public string SYSTEM_NAME
        {
            get { return fSYSTEM_NAME; }
            set { SetPropertyValue<string>(nameof(SYSTEM_NAME), ref fSYSTEM_NAME, value); }
        }
        string fOBJECT_NAME;
        [Size(50)]
        [Persistent(@"object_name")]
        public string OBJECT_NAME
        {
            get { return fOBJECT_NAME; }
            set { SetPropertyValue<string>(nameof(OBJECT_NAME), ref fOBJECT_NAME, value); }
        }
        int fACT_USER;
        [Persistent(@"act_user")]
        public int ACT_USER
        {
            get { return fACT_USER; }
            set { SetPropertyValue<int>(nameof(ACT_USER), ref fACT_USER, value); }
        }
        string fACT_NAME;
        [Size(50)]
        [Persistent(@"act_name")]
        public string ACT_NAME
        {
            get { return fACT_NAME; }
            set { SetPropertyValue<string>(nameof(ACT_NAME), ref fACT_NAME, value); }
        }
        string fACT_DESC;
        [Size(4000)]
        [Persistent(@"act_desc")]
        public string ACT_DESC
        {
            get { return fACT_DESC; }
            set { SetPropertyValue<string>(nameof(ACT_DESC), ref fACT_DESC, value); }
        }
        string fDATA_OBJ;
        [Size(50)]
        [Persistent(@"data_obj")]
        public string DATA_OBJ
        {
            get { return fDATA_OBJ; }
            set { SetPropertyValue<string>(nameof(DATA_OBJ), ref fDATA_OBJ, value); }
        }
        string fDATA_ID;
        [Size(50)]
        [Persistent(@"data_id")]
        public string DATA_ID
        {
            get { return fDATA_ID; }
            set { SetPropertyValue<string>(nameof(DATA_ID), ref fDATA_ID, value); }
        }
        string fREF_ID;
        [Size(50)]
        [Persistent(@"ref_id")]
        public string REF_ID
        {
            get { return fREF_ID; }
            set { SetPropertyValue<string>(nameof(REF_ID), ref fREF_ID, value); }
        }
        string fREQ_IP;
        [Size(50)]
        [Persistent(@"req_ip")]
        public string REQ_IP
        {
            get { return fREQ_IP; }
            set { SetPropertyValue<string>(nameof(REQ_IP), ref fREQ_IP, value); }
        }
    }

}
