//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"adm_user")]
    public partial class ADM_USER : XPLiteObject
    {
        int fUSER_ID;
        [Key(true)]
        [Persistent(@"user_id")]
        public int USER_ID
        {
            get { return fUSER_ID; }
            set { SetPropertyValue<int>(nameof(USER_ID), ref fUSER_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fUSER_NAME;
        [Persistent(@"user_name")]
        public string USER_NAME
        {
            get { return fUSER_NAME; }
            set { SetPropertyValue<string>(nameof(USER_NAME), ref fUSER_NAME, value); }
        }
        string fUSER_PICTURE;
        [Size(5000)]
        [Persistent(@"user_picture")]
        public string USER_PICTURE
        {
            get { return fUSER_PICTURE; }
            set { SetPropertyValue<string>(nameof(USER_PICTURE), ref fUSER_PICTURE, value); }
        }
        string fUSER_LOGIN_FLAG;
        [Size(2)]
        [Persistent(@"user_login_flag")]
        public string USER_LOGIN_FLAG
        {
            get { return fUSER_LOGIN_FLAG; }
            set { SetPropertyValue<string>(nameof(USER_LOGIN_FLAG), ref fUSER_LOGIN_FLAG, value); }
        }
        string fUSER_PASSWORD;
        [Size(255)]
        [Persistent(@"user_password")]
        public string USER_PASSWORD
        {
            get { return fUSER_PASSWORD; }
            set { SetPropertyValue<string>(nameof(USER_PASSWORD), ref fUSER_PASSWORD, value); }
        }
        DateTime fUSER_LOGIN_DATE;
        [Persistent(@"user_login_date")]
        public DateTime USER_LOGIN_DATE
        {
            get { return fUSER_LOGIN_DATE; }
            set { SetPropertyValue<DateTime>(nameof(USER_LOGIN_DATE), ref fUSER_LOGIN_DATE, value); }
        }
        string fUSER_SESSION_ID;
        [Size(500)]
        [Persistent(@"user_session_id")]
        public string USER_SESSION_ID
        {
            get { return fUSER_SESSION_ID; }
            set { SetPropertyValue<string>(nameof(USER_SESSION_ID), ref fUSER_SESSION_ID, value); }
        }
        DateTime fUSER_ACTIVATED_DATE;
        [Persistent(@"user_activated_date")]
        public DateTime USER_ACTIVATED_DATE
        {
            get { return fUSER_ACTIVATED_DATE; }
            set { SetPropertyValue<DateTime>(nameof(USER_ACTIVATED_DATE), ref fUSER_ACTIVATED_DATE, value); }
        }
        DateTime fUSER_CHANGE_DATE;
        [Persistent(@"user_change_date")]
        public DateTime USER_CHANGE_DATE
        {
            get { return fUSER_CHANGE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(USER_CHANGE_DATE), ref fUSER_CHANGE_DATE, value); }
        }
        string fUSER_FORCE_CHANGE;
        [Persistent(@"user_force_change")]
        public string USER_FORCE_CHANGE
        {
            get { return fUSER_FORCE_CHANGE; }
            set { SetPropertyValue<string>(nameof(USER_FORCE_CHANGE), ref fUSER_FORCE_CHANGE, value); }
        }
        string fUSER_APPROVE_FLAG;
        [Size(3)]
        [Persistent(@"user_approve_flag")]
        public string USER_APPROVE_FLAG
        {
            get { return fUSER_APPROVE_FLAG; }
            set { SetPropertyValue<string>(nameof(USER_APPROVE_FLAG), ref fUSER_APPROVE_FLAG, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        [ColumnDbDefaultValue("'a'::bpchar")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        [ColumnDbDefaultValue("'n'::bpchar")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        float? fUSER_IAL;
        [Persistent(@"user_ial")]
        public float? USER_IAL
        {
            get { return fUSER_IAL; }
            set { SetPropertyValue<float?>(nameof(USER_IAL), ref fUSER_IAL, value); }
        }
        float? fUSER_AAL;
        [Persistent(@"user_aal")]
        public float? USER_AAL
        {
            get { return fUSER_AAL; }
            set { SetPropertyValue<float?>(nameof(USER_AAL), ref fUSER_AAL, value); }
        }
        int fUSER_TYPE;
        [Persistent(@"user_type")]
        public int USER_TYPE
        {
            get { return fUSER_TYPE; }
            set { SetPropertyValue<int>(nameof(USER_TYPE), ref fUSER_TYPE, value); }
        }
        string fUSER_REJECT_FLAG;
        [Size(1)]
        [Persistent(@"user_reject_flag")]
        public string USER_REJECT_FLAG
        {
            get { return fUSER_REJECT_FLAG; }
            set { SetPropertyValue<string>(nameof(USER_REJECT_FLAG), ref fUSER_REJECT_FLAG, value); }
        }
        string fUSER_REJECT_REMARK;
        [Size(2000)]
        [Persistent(@"user_reject_remark")]
        public string USER_REJECT_REMARK
        {
            get { return fUSER_REJECT_REMARK; }
            set { SetPropertyValue<string>(nameof(USER_REJECT_REMARK), ref fUSER_REJECT_REMARK, value); }
        }
        int fPERSONAL_APPROVE_ID;
        [Persistent(@"personal_approve_id")]
        public int PERSONAL_APPROVE_ID
        {
            get { return fPERSONAL_APPROVE_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_APPROVE_ID), ref fPERSONAL_APPROVE_ID, value); }
        }
        DateTime fUSER_APPROVE_DATE;
        [Persistent(@"user_approve_date")]
        public DateTime USER_APPROVE_DATE
        {
            get { return fUSER_APPROVE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(USER_APPROVE_DATE), ref fUSER_APPROVE_DATE, value); }
        }
    }

}
