//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"bpm_proc_inst_appointment_attendee")]
    public partial class BPM_PROC_INST_APPOINTMENT_ATTENDEE : XPLiteObject
    {
        int fAPPOINTMENT_ATTENDEE_ID;
        [Key(true)]
        [Persistent(@"appointment_attendee_id")]
        public int APPOINTMENT_ATTENDEE_ID
        {
            get { return fAPPOINTMENT_ATTENDEE_ID; }
            set { SetPropertyValue<int>(nameof(APPOINTMENT_ATTENDEE_ID), ref fAPPOINTMENT_ATTENDEE_ID, value); }
        }
        int fAPPOINTMENT_ID;
        [Persistent(@"appointment_id")]
        public int APPOINTMENT_ID
        {
            get { return fAPPOINTMENT_ID; }
            set { SetPropertyValue<int>(nameof(APPOINTMENT_ID), ref fAPPOINTMENT_ID, value); }
        }
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
    }

}
