//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"bpm_proc_inst_attachment_payment")]
    public partial class BPM_PROC_INST_ATTACHMENT_PAYMENT : XPLiteObject
    {
        int fINST_ATTACHMENT_PAYMENT_ID;
        [Key(true)]
        [Persistent(@"inst_attachment_payment_id")]
        public int INST_ATTACHMENT_PAYMENT_ID
        {
            get { return fINST_ATTACHMENT_PAYMENT_ID; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_PAYMENT_ID), ref fINST_ATTACHMENT_PAYMENT_ID, value); }
        }
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        string fINST_ATTACHMENT_NAME;
        [Size(2000)]
        [Persistent(@"inst_attachment_name")]
        public string INST_ATTACHMENT_NAME
        {
            get { return fINST_ATTACHMENT_NAME; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_NAME), ref fINST_ATTACHMENT_NAME, value); }
        }
        DateTime fINST_ATTACHMENT_DATE;
        [Persistent(@"inst_attachment_date")]
        public DateTime INST_ATTACHMENT_DATE
        {
            get { return fINST_ATTACHMENT_DATE; }
            set { SetPropertyValue<DateTime>(nameof(INST_ATTACHMENT_DATE), ref fINST_ATTACHMENT_DATE, value); }
        }
        string fINST_ATTACHMENT_PATH;
        [Size(4000)]
        [Persistent(@"inst_attachment_path")]
        public string INST_ATTACHMENT_PATH
        {
            get { return fINST_ATTACHMENT_PATH; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_PATH), ref fINST_ATTACHMENT_PATH, value); }
        }
        string fWF_INSTANCE_ID;
        [Size(50)]
        [Persistent(@"wf_instance_id")]
        public string WF_INSTANCE_ID
        {
            get { return fWF_INSTANCE_ID; }
            set { SetPropertyValue<string>(nameof(WF_INSTANCE_ID), ref fWF_INSTANCE_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        int fINST_ATTACHMENT_SIZE;
        [Persistent(@"inst_attachment_size")]
        public int INST_ATTACHMENT_SIZE
        {
            get { return fINST_ATTACHMENT_SIZE; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_SIZE), ref fINST_ATTACHMENT_SIZE, value); }
        }
        int fINST_ATTACHMENT_TYPE_ID;
        [Persistent(@"inst_attachment_type_id")]
        public int INST_ATTACHMENT_TYPE_ID
        {
            get { return fINST_ATTACHMENT_TYPE_ID; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_TYPE_ID), ref fINST_ATTACHMENT_TYPE_ID, value); }
        }
        string fINST_ATTACHMENT_ACTION_FLAG;
        [Persistent(@"inst_attachment_action_flag")]
        public string INST_ATTACHMENT_ACTION_FLAG
        {
            get { return fINST_ATTACHMENT_ACTION_FLAG; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_ACTION_FLAG), ref fINST_ATTACHMENT_ACTION_FLAG, value); }
        }
        string fINST_ATTACHMENT_PAY_NO;
        [Size(500)]
        [Persistent(@"inst_attachment_pay_no")]
        public string INST_ATTACHMENT_PAY_NO
        {
            get { return fINST_ATTACHMENT_PAY_NO; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_PAY_NO), ref fINST_ATTACHMENT_PAY_NO, value); }
        }
        DateTime fINST_ATTACHMENT_PAY_DATE;
        [Persistent(@"inst_attachment_pay_date")]
        public DateTime INST_ATTACHMENT_PAY_DATE
        {
            get { return fINST_ATTACHMENT_PAY_DATE; }
            set { SetPropertyValue<DateTime>(nameof(INST_ATTACHMENT_PAY_DATE), ref fINST_ATTACHMENT_PAY_DATE, value); }
        }
        string fINST_ATTACHMENT_PAY_TIME;
        [Size(50)]
        [Persistent(@"inst_attachment_pay_time")]
        public string INST_ATTACHMENT_PAY_TIME
        {
            get { return fINST_ATTACHMENT_PAY_TIME; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_PAY_TIME), ref fINST_ATTACHMENT_PAY_TIME, value); }
        }
        int fINST_ATTACHMENT_PAY_CHANNEL;
        [Persistent(@"inst_attachment_pay_channel")]
        public int INST_ATTACHMENT_PAY_CHANNEL
        {
            get { return fINST_ATTACHMENT_PAY_CHANNEL; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_PAY_CHANNEL), ref fINST_ATTACHMENT_PAY_CHANNEL, value); }
        }
        int fINST_ATTACHMENT_PAY_TYPE;
        [Persistent(@"inst_attachment_pay_type")]
        public int INST_ATTACHMENT_PAY_TYPE
        {
            get { return fINST_ATTACHMENT_PAY_TYPE; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_PAY_TYPE), ref fINST_ATTACHMENT_PAY_TYPE, value); }
        }
        float fINST_ATTACHMENT_PAY_AMOUNT;
        [Persistent(@"inst_attachment_pay_amount")]
        public float INST_ATTACHMENT_PAY_AMOUNT
        {
            get { return fINST_ATTACHMENT_PAY_AMOUNT; }
            set { SetPropertyValue<float>(nameof(INST_ATTACHMENT_PAY_AMOUNT), ref fINST_ATTACHMENT_PAY_AMOUNT, value); }
        }
        string fINST_ATTACHMENT_PAY_CHANNEL_DETAIL;
        [Size(500)]
        [Persistent(@"inst_attachment_pay_channel_detail")]
        public string INST_ATTACHMENT_PAY_CHANNEL_DETAIL
        {
            get { return fINST_ATTACHMENT_PAY_CHANNEL_DETAIL; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_PAY_CHANNEL_DETAIL), ref fINST_ATTACHMENT_PAY_CHANNEL_DETAIL, value); }
        }
    }

}
