//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"cms_title")]
    public partial class CMS_TITLE : XPLiteObject
    {
        int fTITLE_ID;
        [Key(true)]
        [Persistent(@"title_id")]
        public int TITLE_ID
        {
            get { return fTITLE_ID; }
            set { SetPropertyValue<int>(nameof(TITLE_ID), ref fTITLE_ID, value); }
        }
        string fTITLE_CODE;
        [Size(4)]
        [Persistent(@"title_code")]
        public string TITLE_CODE
        {
            get { return fTITLE_CODE; }
            set { SetPropertyValue<string>(nameof(TITLE_CODE), ref fTITLE_CODE, value); }
        }
        string fTITLE_NAME;
        [Size(200)]
        [Persistent(@"title_name")]
        public string TITLE_NAME
        {
            get { return fTITLE_NAME; }
            set { SetPropertyValue<string>(nameof(TITLE_NAME), ref fTITLE_NAME, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
    }

}
