//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"cms_group_status")]
    public partial class CMS_GROUP_STATUS : XPLiteObject
    {
        int fGROUP_STATUS_ID;
        [Key(true)]
        [Persistent(@"group_status_id")]
        public int GROUP_STATUS_ID
        {
            get { return fGROUP_STATUS_ID; }
            set { SetPropertyValue<int>(nameof(GROUP_STATUS_ID), ref fGROUP_STATUS_ID, value); }
        }
        int fGROUP_SEQ;
        [Persistent(@"group_seq")]
        public int GROUP_SEQ
        {
            get { return fGROUP_SEQ; }
            set { SetPropertyValue<int>(nameof(GROUP_SEQ), ref fGROUP_SEQ, value); }
        }
        string fGROUP_STATUS_CODE;
        [Persistent(@"group_status_code")]
        public string GROUP_STATUS_CODE
        {
            get { return fGROUP_STATUS_CODE; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_CODE), ref fGROUP_STATUS_CODE, value); }
        }
        string fGROUP_STATUS_NAME;
        [Size(200)]
        [Persistent(@"group_status_name")]
        public string GROUP_STATUS_NAME
        {
            get { return fGROUP_STATUS_NAME; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_NAME), ref fGROUP_STATUS_NAME, value); }
        }
        string fGROUP_ICON;
        [Size(200)]
        [Persistent(@"group_icon")]
        public string GROUP_ICON
        {
            get { return fGROUP_ICON; }
            set { SetPropertyValue<string>(nameof(GROUP_ICON), ref fGROUP_ICON, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
    }

}
