//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"cms_position")]
    public partial class CMS_POSITION : XPLiteObject
    {
        int fPOSITION_ID;
        [Key(true)]
        [Persistent(@"position_id")]
        public int POSITION_ID
        {
            get { return fPOSITION_ID; }
            set { SetPropertyValue<int>(nameof(POSITION_ID), ref fPOSITION_ID, value); }
        }
        string fPOSITION_CODE;
        [Persistent(@"position_code")]
        public string POSITION_CODE
        {
            get { return fPOSITION_CODE; }
            set { SetPropertyValue<string>(nameof(POSITION_CODE), ref fPOSITION_CODE, value); }
        }
        string fPOSITION_NAME;
        [Size(500)]
        [Persistent(@"position_name")]
        public string POSITION_NAME
        {
            get { return fPOSITION_NAME; }
            set { SetPropertyValue<string>(nameof(POSITION_NAME), ref fPOSITION_NAME, value); }
        }
        string fPOSITION_STATUS;
        [Persistent(@"position_status")]
        public string POSITION_STATUS
        {
            get { return fPOSITION_STATUS; }
            set { SetPropertyValue<string>(nameof(POSITION_STATUS), ref fPOSITION_STATUS, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
    }

}
