//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using Microsoft.Extensions.Configuration;
namespace SaoTsea.Ds.Api.EntitiesCode
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(BPM_FORM_CATEGORY),
            typeof(BPM_PROC_INST_CHAT),
            typeof(BPM_PROC_INST_APPOINTMENT_ATTENDEE),
            typeof(ADM_USER),
            typeof(CMS_DISTRICT),
            typeof(CMS_ORGANIZE),
            typeof(CMS_PERSONAL),
            typeof(CMS_POSITION),
            typeof(CMS_PROVINCE),
            typeof(CMS_SUB_DISTRICT),
            typeof(CMS_SUB_POSTCODE),
            typeof(CMS_TITLE),
            typeof(BPM_PROC_INST),
            typeof(BPM_PROC_INST_LOG),
            typeof(PERSONAL_EDOC_PKI),
            typeof(BPM_FLOW),
            typeof(BPM_PROC_INST_ATTACHMENT),
            typeof(VIEW_ORGANIZE),
            typeof(VIEW_POSTCODE),
            typeof(VIEW_PROC_INST),
            typeof(VIEW_PROC_INST_CHAT),
            typeof(CMS_STATUS),
            typeof(CMS_GROUP_STATUS),
            typeof(VIEW_STATUS),
            typeof(BPM_PROC_INST_ATTACHMENT_TYPE),
            typeof(VIEW_PROC_INST_ATTACHMENT),
            typeof(BPM_PROC_INST_APPOINTMENT_TYPE),
            typeof(VIEW_PROC_INST_APPOINTMENT),
            typeof(BPM_PROC_INST_APPOINTMENT_STATUS),
            typeof(VIEW_COUNT_STATUS_PROC_INST),
            typeof(VIEW_PROC_INST_LOG),
            typeof(BPM_PROC_INST_APPOINTMENT),
            typeof(VIEW_MODULE_INFO),
            typeof(VIEW_MODULE_PRIV),
            typeof(ADM_LOG),
            typeof(ADM_MODULE_INFO),
            typeof(ADM_MODULE_PRIV),
            typeof(ADM_PERMISSION_INFO),
            typeof(ADM_ROLE_INFO),
            typeof(ADM_ROLE_PRIV),
            typeof(ADM_USER_ROLE),
            typeof(VIEW_USER_ROLE),
            typeof(VIEW_ROLE_PRIV),
            typeof(BPM_FLOW_GROUP),
            typeof(BPM_PROC_INST_CASE_RELATION),
            typeof(VIEW_CASE_RELATION),
            typeof(VIEW_PROC_FLOW),
            typeof(VIEW_CASE_RELATION_APPOINTMENT),
            typeof(ADM_APP_INFO),
            typeof(ADM_APP_ORG),
            typeof(VIEW_APP_ORG),
            typeof(VIEW_CASE_RELATION_DISTINCT),
            typeof(BPM_NOTIFICATION_TO),
            typeof(BPM_NOTIFICATION),
            typeof(VIEW_NOTIFICATION),
            typeof(CMS_ORGANIZE_PROVINCE),
            typeof(VIEW_ORGANIZE_PROVINCE),
            typeof(CMS_HOLIDAY_INFO),
            typeof(VIEW_HOLIDAY_INFO),
            typeof(CMS_POSITION_MNG),
            typeof(BPM_PROC_INST_ATTACHMENT_OFFICER),
            typeof(VIEW_PROC_INST_ATTACHMENT_OFFICER),
            typeof(ADM_SSO),
            typeof(ADM_SYSTEM_INFO),
            typeof(BPM_PROC_INST_ATTACHMENT_PAYMENT),
            typeof(BPM_PROC_INST_ATTACHMENT_TYPE_FORM),
            typeof(VIEW_ATTACHMENT_TYPE_FORM),
            typeof(VIEW_DOC_ATTACHMENT_ALL),
            typeof(BPM_FORM),
            typeof(VIEW_COUNT_GROUP_STATUS_PROC_INST),
            typeof(VIEW_PROC_INST_HISTORY),
            typeof(VIEW_PROC_INST_TRACKING),
            typeof(VIEW_EDOC_ASSIGN),
            typeof(VIEW_PROC_INST_ASS),
            typeof(VIEW_SSO_USER_OFFICER),
            typeof(VIEW_USER_ROLE_ALL),
            typeof(VIEW_PROC_INST_V2),
            typeof(VIEW_PERSONAL)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public const string ConnectionStringName = "POSTGRES";
        public static void Connect(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = GetConnectionProvider(configuration, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(configuration.GetConnectionString(ConnectionStringName), autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
        }
    }

}
