//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DevExpress.Xpo;

namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"edoc_txn_assign")]
    public partial class EDOC_TXN_ASSIGN : XPLiteObject
    {
        int fEDOC_ASSIGN_ID;
        [Key(true)]
        [Persistent(@"edoc_assign_id")]
        public int EDOC_ASSIGN_ID
        {
            get { return fEDOC_ASSIGN_ID; }
            set { SetPropertyValue<int>(nameof(EDOC_ASSIGN_ID), ref fEDOC_ASSIGN_ID, value); }
        }
        int fASSIGNER_PERSONAL_ID;
        [Persistent(@"assigner_personal_id")]
        public int ASSIGNER_PERSONAL_ID
        {
            get { return fASSIGNER_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(ASSIGNER_PERSONAL_ID), ref fASSIGNER_PERSONAL_ID, value); }
        }
        int fASSIGNEE_PERSONAL_ID;
        [Persistent(@"assignee_personal_id")]
        public int ASSIGNEE_PERSONAL_ID
        {
            get { return fASSIGNEE_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(ASSIGNEE_PERSONAL_ID), ref fASSIGNEE_PERSONAL_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fDESCRIPTION;
        [Size(5000)]
        [Persistent(@"description")]
        public string DESCRIPTION
        {
            get { return fDESCRIPTION; }
            set { SetPropertyValue<string>(nameof(DESCRIPTION), ref fDESCRIPTION, value); }
        }
        string fATTACHMENT_PATH;
        [Size(5000)]
        [Persistent(@"attachment_path")]
        public string ATTACHMENT_PATH
        {
            get { return fATTACHMENT_PATH; }
            set { SetPropertyValue<string>(nameof(ATTACHMENT_PATH), ref fATTACHMENT_PATH, value); }
        }
        string fATTACHMENT_HASH;
        [Size(500)]
        [Persistent(@"attachment_hash")]
        public string ATTACHMENT_HASH
        {
            get { return fATTACHMENT_HASH; }
            set { SetPropertyValue<string>(nameof(ATTACHMENT_HASH), ref fATTACHMENT_HASH, value); }
        }
        string fEDOC_ASSIGN_SIGNATURE;
        [Size(2000)]
        [Persistent(@"edoc_assign_signature")]
        public string EDOC_ASSIGN_SIGNATURE
        {
            get { return fEDOC_ASSIGN_SIGNATURE; }
            set { SetPropertyValue<string>(nameof(EDOC_ASSIGN_SIGNATURE), ref fEDOC_ASSIGN_SIGNATURE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        DateTime fSTART_DATE;
        [Persistent(@"start_date")]
        public DateTime START_DATE
        {
            get { return fSTART_DATE; }
            set { SetPropertyValue<DateTime>(nameof(START_DATE), ref fSTART_DATE, value); }
        }
        DateTime fEND_DATE;
        [Persistent(@"end_date")]
        public DateTime END_DATE
        {
            get { return fEND_DATE; }
            set { SetPropertyValue<DateTime>(nameof(END_DATE), ref fEND_DATE, value); }
        }
        string fDESCRIPTION_CANCEL;
        [Persistent(@"description_cancel")]
        public string DESCRIPTION_CANCEL
        {
            get { return fDESCRIPTION_CANCEL; }
            set { SetPropertyValue<string>(nameof(DESCRIPTION_CANCEL), ref fDESCRIPTION_CANCEL, value); }
        }
        string fCANCEL_FLAG;
        [Persistent(@"cancel_flag")]
        public string CANCEL_FLAG
        {
            get { return fCANCEL_FLAG; }
            set { SetPropertyValue<string>(nameof(CANCEL_FLAG), ref fCANCEL_FLAG, value); }
        }
    }

}
