//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"personal_edoc_pki")]
    public partial class PERSONAL_EDOC_PKI : XPLiteObject
    {
        int fPERSONAL_PKI_ID;
        [Key(true)]
        [Persistent(@"personal_pki_id")]
        public int PERSONAL_PKI_ID
        {
            get { return fPERSONAL_PKI_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_PKI_ID), ref fPERSONAL_PKI_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fPKI_PATH;
        [Size(2000)]
        [Persistent(@"pki_path")]
        public string PKI_PATH
        {
            get { return fPKI_PATH; }
            set { SetPropertyValue<string>(nameof(PKI_PATH), ref fPKI_PATH, value); }
        }
        string fPKI_PASSWD;
        [Size(2000)]
        [Persistent(@"pki_passwd")]
        public string PKI_PASSWD
        {
            get { return fPKI_PASSWD; }
            set { SetPropertyValue<string>(nameof(PKI_PASSWD), ref fPKI_PASSWD, value); }
        }
        string fPKI_SIGNATURE;
        [Size(2000)]
        [Persistent(@"pki_signature")]
        public string PKI_SIGNATURE
        {
            get { return fPKI_SIGNATURE; }
            set { SetPropertyValue<string>(nameof(PKI_SIGNATURE), ref fPKI_SIGNATURE, value); }
        }
        string fPKI_PINCODE;
        [Size(20)]
        [Persistent(@"pki_pincode")]
        public string PKI_PINCODE
        {
            get { return fPKI_PINCODE; }
            set { SetPropertyValue<string>(nameof(PKI_PINCODE), ref fPKI_PINCODE, value); }
        }
        DateTime fPKI_EXPIRE_DATE;
        [Persistent(@"pki_expire_date")]
        public DateTime PKI_EXPIRE_DATE
        {
            get { return fPKI_EXPIRE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(PKI_EXPIRE_DATE), ref fPKI_EXPIRE_DATE, value); }
        }
        int fPKI_TYPE;
        [Persistent(@"pki_type")]
        public int PKI_TYPE
        {
            get { return fPKI_TYPE; }
            set { SetPropertyValue<int>(nameof(PKI_TYPE), ref fPKI_TYPE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
    }

}
