//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_role_priv")]
    public partial class VIEW_ROLE_PRIV : XPLiteObject
    {
        int fROLE_PRIV_ID;
        [Key]
        [Persistent(@"role_priv_id")]
        public int ROLE_PRIV_ID
        {
            get { return fROLE_PRIV_ID; }
            set { SetPropertyValue<int>(nameof(ROLE_PRIV_ID), ref fROLE_PRIV_ID, value); }
        }
        int fROLE_ID;
        [Persistent(@"role_id")]
        public int ROLE_ID
        {
            get { return fROLE_ID; }
            set { SetPropertyValue<int>(nameof(ROLE_ID), ref fROLE_ID, value); }
        }
        int fMODULE_PRIV_ID;
        [Persistent(@"module_priv_id")]
        public int MODULE_PRIV_ID
        {
            get { return fMODULE_PRIV_ID; }
            set { SetPropertyValue<int>(nameof(MODULE_PRIV_ID), ref fMODULE_PRIV_ID, value); }
        }
        string fPRIV_FLAG;
        [Persistent(@"priv_flag")]
        public string PRIV_FLAG
        {
            get { return fPRIV_FLAG; }
            set { SetPropertyValue<string>(nameof(PRIV_FLAG), ref fPRIV_FLAG, value); }
        }
        string fMODULE_NAME;
        [Size(500)]
        [Persistent(@"module_name")]
        public string MODULE_NAME
        {
            get { return fMODULE_NAME; }
            set { SetPropertyValue<string>(nameof(MODULE_NAME), ref fMODULE_NAME, value); }
        }
        int? fAPP_ID;
        [Persistent(@"app_id")]
        public int? APP_ID
        {
            get { return fAPP_ID; }
            set { SetPropertyValue<int?>(nameof(APP_ID), ref fAPP_ID, value); }
        }
        int fMODULE_ID;
        [Persistent(@"module_id")]
        public int MODULE_ID
        {
            get { return fMODULE_ID; }
            set { SetPropertyValue<int>(nameof(MODULE_ID), ref fMODULE_ID, value); }
        }
        string fPERMISSION_NAME;
        [Size(500)]
        [Persistent(@"permission_name")]
        public string PERMISSION_NAME
        {
            get { return fPERMISSION_NAME; }
            set { SetPropertyValue<string>(nameof(PERMISSION_NAME), ref fPERMISSION_NAME, value); }
        }
        int fPERMISSION_ID;
        [Persistent(@"permission_id")]
        public int PERMISSION_ID
        {
            get { return fPERMISSION_ID; }
            set { SetPropertyValue<int>(nameof(PERMISSION_ID), ref fPERMISSION_ID, value); }
        }
        string fMODULE_ICON;
        [Persistent(@"module_icon")]
        public string MODULE_ICON
        {
            get { return fMODULE_ICON; }
            set { SetPropertyValue<string>(nameof(MODULE_ICON), ref fMODULE_ICON, value); }
        }
        int fMODULE_LEVEL;
        [Persistent(@"module_level")]
        public int MODULE_LEVEL
        {
            get { return fMODULE_LEVEL; }
            set { SetPropertyValue<int>(nameof(MODULE_LEVEL), ref fMODULE_LEVEL, value); }
        }
        string fMODULE_SEQ;
        [Size(10)]
        [Persistent(@"module_seq")]
        public string MODULE_SEQ
        {
            get { return fMODULE_SEQ; }
            set { SetPropertyValue<string>(nameof(MODULE_SEQ), ref fMODULE_SEQ, value); }
        }
        int fMODULE_PARENT_ID;
        [Persistent(@"module_parent_id")]
        public int MODULE_PARENT_ID
        {
            get { return fMODULE_PARENT_ID; }
            set { SetPropertyValue<int>(nameof(MODULE_PARENT_ID), ref fMODULE_PARENT_ID, value); }
        }
    }

}
