//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_inst_chat")]
    public partial class VIEW_PROC_INST_CHAT : XPLiteObject
    {
        int fINST_CHAT_ID;
        [Key]
        [Persistent(@"inst_chat_id")]
        public int INST_CHAT_ID
        {
            get { return fINST_CHAT_ID; }
            set { SetPropertyValue<int>(nameof(INST_CHAT_ID), ref fINST_CHAT_ID, value); }
        }
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        string fINST_CHAT_MASSAGE;
        [Size(4000)]
        [Persistent(@"inst_chat_massage")]
        public string INST_CHAT_MASSAGE
        {
            get { return fINST_CHAT_MASSAGE; }
            set { SetPropertyValue<string>(nameof(INST_CHAT_MASSAGE), ref fINST_CHAT_MASSAGE, value); }
        }
        int fSENDER_ID;
        [Persistent(@"sender_id")]
        public int SENDER_ID
        {
            get { return fSENDER_ID; }
            set { SetPropertyValue<int>(nameof(SENDER_ID), ref fSENDER_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fPERSONAL_FULL_NAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"personal_full_name")]
        public string PERSONAL_FULL_NAME
        {
            get { return fPERSONAL_FULL_NAME; }
            set { SetPropertyValue<string>(nameof(PERSONAL_FULL_NAME), ref fPERSONAL_FULL_NAME, value); }
        }
        string fUSER_NAME;
        [Persistent(@"user_name")]
        public string USER_NAME
        {
            get { return fUSER_NAME; }
            set { SetPropertyValue<string>(nameof(USER_NAME), ref fUSER_NAME, value); }
        }
        string fPERSONAL_FNAME_THA;
        [Size(255)]
        [Persistent(@"personal_fname_tha")]
        public string PERSONAL_FNAME_THA
        {
            get { return fPERSONAL_FNAME_THA; }
            set { SetPropertyValue<string>(nameof(PERSONAL_FNAME_THA), ref fPERSONAL_FNAME_THA, value); }
        }
        string fPERSONAL_PICTURE;
        [Size(2000)]
        [Persistent(@"personal_picture")]
        public string PERSONAL_PICTURE
        {
            get { return fPERSONAL_PICTURE; }
            set { SetPropertyValue<string>(nameof(PERSONAL_PICTURE), ref fPERSONAL_PICTURE, value); }
        }
    }

}
