//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_inst_appointment")]
    public partial class VIEW_PROC_INST_APPOINTMENT : XPLiteObject
    {
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        int fAPPOINTMENT_ID;
        [Key]
        [Persistent(@"appointment_id")]
        public int APPOINTMENT_ID
        {
            get { return fAPPOINTMENT_ID; }
            set { SetPropertyValue<int>(nameof(APPOINTMENT_ID), ref fAPPOINTMENT_ID, value); }
        }
        int fAPPOINTMENT_TYPE_ID;
        [Persistent(@"appointment_type_id")]
        public int APPOINTMENT_TYPE_ID
        {
            get { return fAPPOINTMENT_TYPE_ID; }
            set { SetPropertyValue<int>(nameof(APPOINTMENT_TYPE_ID), ref fAPPOINTMENT_TYPE_ID, value); }
        }
        DateTime fAPPOINTMENT_DATE;
        [Persistent(@"appointment_date")]
        public DateTime APPOINTMENT_DATE
        {
            get { return fAPPOINTMENT_DATE; }
            set { SetPropertyValue<DateTime>(nameof(APPOINTMENT_DATE), ref fAPPOINTMENT_DATE, value); }
        }
        int fCONTACT_ID;
        [Persistent(@"contact_id")]
        public int CONTACT_ID
        {
            get { return fCONTACT_ID; }
            set { SetPropertyValue<int>(nameof(CONTACT_ID), ref fCONTACT_ID, value); }
        }
        int fAPP_PERSONAL_ID;
        [Persistent(@"app_personal_id")]
        public int APP_PERSONAL_ID
        {
            get { return fAPP_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(APP_PERSONAL_ID), ref fAPP_PERSONAL_ID, value); }
        }
        string fAPPOINTMENT_PERSONAL_TEL_NO;
        [Size(10)]
        [Persistent(@"appointment_personal_tel_no")]
        public string APPOINTMENT_PERSONAL_TEL_NO
        {
            get { return fAPPOINTMENT_PERSONAL_TEL_NO; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_PERSONAL_TEL_NO), ref fAPPOINTMENT_PERSONAL_TEL_NO, value); }
        }
        string fAPPOINTMENT_DETAIL;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"appointment_detail")]
        public string APPOINTMENT_DETAIL
        {
            get { return fAPPOINTMENT_DETAIL; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_DETAIL), ref fAPPOINTMENT_DETAIL, value); }
        }
        string fAPPOINTMENT_RESULT;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"appointment_result")]
        public string APPOINTMENT_RESULT
        {
            get { return fAPPOINTMENT_RESULT; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_RESULT), ref fAPPOINTMENT_RESULT, value); }
        }
        int fAPP_STATUS_ID;
        [Persistent(@"app_status_id")]
        public int APP_STATUS_ID
        {
            get { return fAPP_STATUS_ID; }
            set { SetPropertyValue<int>(nameof(APP_STATUS_ID), ref fAPP_STATUS_ID, value); }
        }
        DateTime fAPPOINTMENT_CASE_STATUS_DATETIME;
        [Persistent(@"appointment_case_status_datetime")]
        public DateTime APPOINTMENT_CASE_STATUS_DATETIME
        {
            get { return fAPPOINTMENT_CASE_STATUS_DATETIME; }
            set { SetPropertyValue<DateTime>(nameof(APPOINTMENT_CASE_STATUS_DATETIME), ref fAPPOINTMENT_CASE_STATUS_DATETIME, value); }
        }
        string fAPPOINTMENT_ASSIGNE_STATION;
        [Size(500)]
        [Persistent(@"appointment_assigne_station")]
        public string APPOINTMENT_ASSIGNE_STATION
        {
            get { return fAPPOINTMENT_ASSIGNE_STATION; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_ASSIGNE_STATION), ref fAPPOINTMENT_ASSIGNE_STATION, value); }
        }
        char fAPPOINTMENT_ALERT_FLAG;
        [Persistent(@"appointment_alert_flag")]
        public char APPOINTMENT_ALERT_FLAG
        {
            get { return fAPPOINTMENT_ALERT_FLAG; }
            set { SetPropertyValue<char>(nameof(APPOINTMENT_ALERT_FLAG), ref fAPPOINTMENT_ALERT_FLAG, value); }
        }
        DateTime fAPPOINTMENT_ALERT_DATE;
        [Persistent(@"appointment_alert_date")]
        public DateTime APPOINTMENT_ALERT_DATE
        {
            get { return fAPPOINTMENT_ALERT_DATE; }
            set { SetPropertyValue<DateTime>(nameof(APPOINTMENT_ALERT_DATE), ref fAPPOINTMENT_ALERT_DATE, value); }
        }
        string fAPPOINTMENT_ALERT_DETAIL;
        [Size(500)]
        [Persistent(@"appointment_alert_detail")]
        public string APPOINTMENT_ALERT_DETAIL
        {
            get { return fAPPOINTMENT_ALERT_DETAIL; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_ALERT_DETAIL), ref fAPPOINTMENT_ALERT_DETAIL, value); }
        }
        char fAPPOINTMENT_REFER_FLAG;
        [Persistent(@"appointment_refer_flag")]
        public char APPOINTMENT_REFER_FLAG
        {
            get { return fAPPOINTMENT_REFER_FLAG; }
            set { SetPropertyValue<char>(nameof(APPOINTMENT_REFER_FLAG), ref fAPPOINTMENT_REFER_FLAG, value); }
        }
        int fREF_INST_ID;
        [Persistent(@"ref_inst_id")]
        public int REF_INST_ID
        {
            get { return fREF_INST_ID; }
            set { SetPropertyValue<int>(nameof(REF_INST_ID), ref fREF_INST_ID, value); }
        }
        int fCREATE_PERSONAL_ID;
        [Persistent(@"create_personal_id")]
        public int CREATE_PERSONAL_ID
        {
            get { return fCREATE_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_PERSONAL_ID), ref fCREATE_PERSONAL_ID, value); }
        }
        char fAPP_RECORD_STATUS;
        [Persistent(@"app_record_status")]
        public char APP_RECORD_STATUS
        {
            get { return fAPP_RECORD_STATUS; }
            set { SetPropertyValue<char>(nameof(APP_RECORD_STATUS), ref fAPP_RECORD_STATUS, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        string fCONTACT_FULLNAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"contact_fullname")]
        public string CONTACT_FULLNAME
        {
            get { return fCONTACT_FULLNAME; }
            set { SetPropertyValue<string>(nameof(CONTACT_FULLNAME), ref fCONTACT_FULLNAME, value); }
        }
        string fAPP_PERSONAL_FULLNAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"app_personal_fullname")]
        public string APP_PERSONAL_FULLNAME
        {
            get { return fAPP_PERSONAL_FULLNAME; }
            set { SetPropertyValue<string>(nameof(APP_PERSONAL_FULLNAME), ref fAPP_PERSONAL_FULLNAME, value); }
        }
        int fFLOW_ID;
        [Persistent(@"flow_id")]
        public int FLOW_ID
        {
            get { return fFLOW_ID; }
            set { SetPropertyValue<int>(nameof(FLOW_ID), ref fFLOW_ID, value); }
        }
        int fCATEGORY_ID;
        [Persistent(@"category_id")]
        public int CATEGORY_ID
        {
            get { return fCATEGORY_ID; }
            set { SetPropertyValue<int>(nameof(CATEGORY_ID), ref fCATEGORY_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        int fORG_ID;
        [Persistent(@"org_id")]
        public int ORG_ID
        {
            get { return fORG_ID; }
            set { SetPropertyValue<int>(nameof(ORG_ID), ref fORG_ID, value); }
        }
        string fTRACKING_CODE;
        [Size(30)]
        [Persistent(@"tracking_code")]
        public string TRACKING_CODE
        {
            get { return fTRACKING_CODE; }
            set { SetPropertyValue<string>(nameof(TRACKING_CODE), ref fTRACKING_CODE, value); }
        }
        string fSTATUS_CODE;
        [Size(3)]
        [Persistent(@"status_code")]
        public string STATUS_CODE
        {
            get { return fSTATUS_CODE; }
            set { SetPropertyValue<string>(nameof(STATUS_CODE), ref fSTATUS_CODE, value); }
        }
        string fGROUP_STATUS_CODE;
        [Size(3)]
        [Persistent(@"group_status_code")]
        public string GROUP_STATUS_CODE
        {
            get { return fGROUP_STATUS_CODE; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_CODE), ref fGROUP_STATUS_CODE, value); }
        }
        int fDATA_ID;
        [Persistent(@"data_id")]
        public int DATA_ID
        {
            get { return fDATA_ID; }
            set { SetPropertyValue<int>(nameof(DATA_ID), ref fDATA_ID, value); }
        }
        string fSYSTEM_CODE;
        [Size(10)]
        [Persistent(@"system_code")]
        public string SYSTEM_CODE
        {
            get { return fSYSTEM_CODE; }
            set { SetPropertyValue<string>(nameof(SYSTEM_CODE), ref fSYSTEM_CODE, value); }
        }
        string fDOCUMENT_ID;
        [Size(50)]
        [Persistent(@"document_id")]
        public string DOCUMENT_ID
        {
            get { return fDOCUMENT_ID; }
            set { SetPropertyValue<string>(nameof(DOCUMENT_ID), ref fDOCUMENT_ID, value); }
        }
        string fWF_INSTANCE_ID;
        [Size(50)]
        [Persistent(@"wf_instance_id")]
        public string WF_INSTANCE_ID
        {
            get { return fWF_INSTANCE_ID; }
            set { SetPropertyValue<string>(nameof(WF_INSTANCE_ID), ref fWF_INSTANCE_ID, value); }
        }
        string fWF_DEFINITION_ID;
        [Size(150)]
        [Persistent(@"wf_definition_id")]
        public string WF_DEFINITION_ID
        {
            get { return fWF_DEFINITION_ID; }
            set { SetPropertyValue<string>(nameof(WF_DEFINITION_ID), ref fWF_DEFINITION_ID, value); }
        }
        string fREMARK;
        [Size(2000)]
        [Persistent(@"remark")]
        public string REMARK
        {
            get { return fREMARK; }
            set { SetPropertyValue<string>(nameof(REMARK), ref fREMARK, value); }
        }
        string fFORM_NAME;
        [Size(500)]
        [Persistent(@"form_name")]
        public string FORM_NAME
        {
            get { return fFORM_NAME; }
            set { SetPropertyValue<string>(nameof(FORM_NAME), ref fFORM_NAME, value); }
        }
        string fFLOW_NAME;
        [Size(500)]
        [Persistent(@"flow_name")]
        public string FLOW_NAME
        {
            get { return fFLOW_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_NAME), ref fFLOW_NAME, value); }
        }
        string fCATEGORY_NAME;
        [Size(500)]
        [Persistent(@"category_name")]
        public string CATEGORY_NAME
        {
            get { return fCATEGORY_NAME; }
            set { SetPropertyValue<string>(nameof(CATEGORY_NAME), ref fCATEGORY_NAME, value); }
        }
        string fSTATUS_NAME;
        [Size(200)]
        [Persistent(@"status_name")]
        public string STATUS_NAME
        {
            get { return fSTATUS_NAME; }
            set { SetPropertyValue<string>(nameof(STATUS_NAME), ref fSTATUS_NAME, value); }
        }
        string fCASE_PERSONAL_FULLNAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"case_personal_fullname")]
        public string CASE_PERSONAL_FULLNAME
        {
            get { return fCASE_PERSONAL_FULLNAME; }
            set { SetPropertyValue<string>(nameof(CASE_PERSONAL_FULLNAME), ref fCASE_PERSONAL_FULLNAME, value); }
        }
        string fAPPOINTMENT_TYPE_NAME;
        [Size(200)]
        [Persistent(@"appointment_type_name")]
        public string APPOINTMENT_TYPE_NAME
        {
            get { return fAPPOINTMENT_TYPE_NAME; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_TYPE_NAME), ref fAPPOINTMENT_TYPE_NAME, value); }
        }
        int fFORM_ID;
        [Persistent(@"form_id")]
        public int FORM_ID
        {
            get { return fFORM_ID; }
            set { SetPropertyValue<int>(nameof(FORM_ID), ref fFORM_ID, value); }
        }
        string fFORM_IO_ID;
        [Size(24)]
        [Persistent(@"form_io_id")]
        public string FORM_IO_ID
        {
            get { return fFORM_IO_ID; }
            set { SetPropertyValue<string>(nameof(FORM_IO_ID), ref fFORM_IO_ID, value); }
        }
        string fAPP_STATUS_NAME;
        [Size(200)]
        [Persistent(@"app_status_name")]
        public string APP_STATUS_NAME
        {
            get { return fAPP_STATUS_NAME; }
            set { SetPropertyValue<string>(nameof(APP_STATUS_NAME), ref fAPP_STATUS_NAME, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fCASE_PERSONAL_EMAIL;
        [Persistent(@"case_personal_email")]
        public string CASE_PERSONAL_EMAIL
        {
            get { return fCASE_PERSONAL_EMAIL; }
            set { SetPropertyValue<string>(nameof(CASE_PERSONAL_EMAIL), ref fCASE_PERSONAL_EMAIL, value); }
        }
        string fAPPOINTMENT_DATE_CHOOSE;
        [Persistent(@"appointment_date_choose")]
        public string APPOINTMENT_DATE_CHOOSE
        {
            get { return fAPPOINTMENT_DATE_CHOOSE; }
            set { SetPropertyValue<string>(nameof(APPOINTMENT_DATE_CHOOSE), ref fAPPOINTMENT_DATE_CHOOSE, value); }
        }
    }

}
