//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_postcode")]
    public partial class VIEW_POSTCODE : XPLiteObject
    {
        int fPOSTCODE_ID;
        [Key]
        [Persistent(@"postcode_id")]
        public int POSTCODE_ID
        {
            get { return fPOSTCODE_ID; }
            set { SetPropertyValue<int>(nameof(POSTCODE_ID), ref fPOSTCODE_ID, value); }
        }
        int fPOSTCODE_CODE;
        [Persistent(@"postcode_code")]
        public int POSTCODE_CODE
        {
            get { return fPOSTCODE_CODE; }
            set { SetPropertyValue<int>(nameof(POSTCODE_CODE), ref fPOSTCODE_CODE, value); }
        }
        int fPROVINCE_ID;
        [Persistent(@"province_id")]
        public int PROVINCE_ID
        {
            get { return fPROVINCE_ID; }
            set { SetPropertyValue<int>(nameof(PROVINCE_ID), ref fPROVINCE_ID, value); }
        }
        int fDISTRICT_ID;
        [Persistent(@"district_id")]
        public int DISTRICT_ID
        {
            get { return fDISTRICT_ID; }
            set { SetPropertyValue<int>(nameof(DISTRICT_ID), ref fDISTRICT_ID, value); }
        }
        int fSUB_DISTRICT_ID;
        [Persistent(@"sub_district_id")]
        public int SUB_DISTRICT_ID
        {
            get { return fSUB_DISTRICT_ID; }
            set { SetPropertyValue<int>(nameof(SUB_DISTRICT_ID), ref fSUB_DISTRICT_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fSUB_DISTRICT_NAME_THA;
        [Size(500)]
        [Persistent(@"sub_district_name_tha")]
        public string SUB_DISTRICT_NAME_THA
        {
            get { return fSUB_DISTRICT_NAME_THA; }
            set { SetPropertyValue<string>(nameof(SUB_DISTRICT_NAME_THA), ref fSUB_DISTRICT_NAME_THA, value); }
        }
    }

}
