//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_inst_history")]
    public partial class VIEW_PROC_INST_HISTORY : XPLiteObject
    {
        int fINST_ID;
        [Key]
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        int fFLOW_ID;
        [Persistent(@"flow_id")]
        public int FLOW_ID
        {
            get { return fFLOW_ID; }
            set { SetPropertyValue<int>(nameof(FLOW_ID), ref fFLOW_ID, value); }
        }
        int fFORM_ID;
        [Persistent(@"form_id")]
        public int FORM_ID
        {
            get { return fFORM_ID; }
            set { SetPropertyValue<int>(nameof(FORM_ID), ref fFORM_ID, value); }
        }
        int fCATEGORY_ID;
        [Persistent(@"category_id")]
        public int CATEGORY_ID
        {
            get { return fCATEGORY_ID; }
            set { SetPropertyValue<int>(nameof(CATEGORY_ID), ref fCATEGORY_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        int fORG_ID;
        [Persistent(@"org_id")]
        public int ORG_ID
        {
            get { return fORG_ID; }
            set { SetPropertyValue<int>(nameof(ORG_ID), ref fORG_ID, value); }
        }
        string fTRACKING_CODE;
        [Size(30)]
        [Persistent(@"tracking_code")]
        public string TRACKING_CODE
        {
            get { return fTRACKING_CODE; }
            set { SetPropertyValue<string>(nameof(TRACKING_CODE), ref fTRACKING_CODE, value); }
        }
        string fSTATUS_CODE;
        [Size(3)]
        [Persistent(@"status_code")]
        public string STATUS_CODE
        {
            get { return fSTATUS_CODE; }
            set { SetPropertyValue<string>(nameof(STATUS_CODE), ref fSTATUS_CODE, value); }
        }
        string fGROUP_STATUS_CODE;
        [Size(3)]
        [Persistent(@"group_status_code")]
        public string GROUP_STATUS_CODE
        {
            get { return fGROUP_STATUS_CODE; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_CODE), ref fGROUP_STATUS_CODE, value); }
        }
        int fDATA_ID;
        [Persistent(@"data_id")]
        public int DATA_ID
        {
            get { return fDATA_ID; }
            set { SetPropertyValue<int>(nameof(DATA_ID), ref fDATA_ID, value); }
        }
        string fSYSTEM_CODE;
        [Size(10)]
        [Persistent(@"system_code")]
        public string SYSTEM_CODE
        {
            get { return fSYSTEM_CODE; }
            set { SetPropertyValue<string>(nameof(SYSTEM_CODE), ref fSYSTEM_CODE, value); }
        }
        string fDOCUMENT_ID;
        [Size(50)]
        [Persistent(@"document_id")]
        public string DOCUMENT_ID
        {
            get { return fDOCUMENT_ID; }
            set { SetPropertyValue<string>(nameof(DOCUMENT_ID), ref fDOCUMENT_ID, value); }
        }
        string fWF_INSTANCE_ID;
        [Size(50)]
        [Persistent(@"wf_instance_id")]
        public string WF_INSTANCE_ID
        {
            get { return fWF_INSTANCE_ID; }
            set { SetPropertyValue<string>(nameof(WF_INSTANCE_ID), ref fWF_INSTANCE_ID, value); }
        }
        string fWF_DEFINITION_ID;
        [Size(150)]
        [Persistent(@"wf_definition_id")]
        public string WF_DEFINITION_ID
        {
            get { return fWF_DEFINITION_ID; }
            set { SetPropertyValue<string>(nameof(WF_DEFINITION_ID), ref fWF_DEFINITION_ID, value); }
        }
        string fREMARK;
        [Size(2000)]
        [Persistent(@"remark")]
        public string REMARK
        {
            get { return fREMARK; }
            set { SetPropertyValue<string>(nameof(REMARK), ref fREMARK, value); }
        }
        int fOFFICER_ID;
        [Persistent(@"officer_id")]
        public int OFFICER_ID
        {
            get { return fOFFICER_ID; }
            set { SetPropertyValue<int>(nameof(OFFICER_ID), ref fOFFICER_ID, value); }
        }
        string fEXT1;
        [Size(255)]
        [Persistent(@"ext1")]
        public string EXT1
        {
            get { return fEXT1; }
            set { SetPropertyValue<string>(nameof(EXT1), ref fEXT1, value); }
        }
        string fEXT2;
        [Size(255)]
        [Persistent(@"ext2")]
        public string EXT2
        {
            get { return fEXT2; }
            set { SetPropertyValue<string>(nameof(EXT2), ref fEXT2, value); }
        }
        string fEXT3;
        [Size(255)]
        [Persistent(@"ext3")]
        public string EXT3
        {
            get { return fEXT3; }
            set { SetPropertyValue<string>(nameof(EXT3), ref fEXT3, value); }
        }
        string fEXT4;
        [Size(255)]
        [Persistent(@"ext4")]
        public string EXT4
        {
            get { return fEXT4; }
            set { SetPropertyValue<string>(nameof(EXT4), ref fEXT4, value); }
        }
        string fEXT5;
        [Size(255)]
        [Persistent(@"ext5")]
        public string EXT5
        {
            get { return fEXT5; }
            set { SetPropertyValue<string>(nameof(EXT5), ref fEXT5, value); }
        }
        string fOPTIONAL_DATA;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"optional_data")]
        public string OPTIONAL_DATA
        {
            get { return fOPTIONAL_DATA; }
            set { SetPropertyValue<string>(nameof(OPTIONAL_DATA), ref fOPTIONAL_DATA, value); }
        }
        string fFORM_NAME;
        [Size(500)]
        [Persistent(@"form_name")]
        public string FORM_NAME
        {
            get { return fFORM_NAME; }
            set { SetPropertyValue<string>(nameof(FORM_NAME), ref fFORM_NAME, value); }
        }
        string fFLOW_NAME;
        [Size(500)]
        [Persistent(@"flow_name")]
        public string FLOW_NAME
        {
            get { return fFLOW_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_NAME), ref fFLOW_NAME, value); }
        }
        string fPERSONAL_FULL_NAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"personal_full_name")]
        public string PERSONAL_FULL_NAME
        {
            get { return fPERSONAL_FULL_NAME; }
            set { SetPropertyValue<string>(nameof(PERSONAL_FULL_NAME), ref fPERSONAL_FULL_NAME, value); }
        }
        string fORGANIZE_NAME_THA;
        [Size(500)]
        [Persistent(@"organize_name_tha")]
        public string ORGANIZE_NAME_THA
        {
            get { return fORGANIZE_NAME_THA; }
            set { SetPropertyValue<string>(nameof(ORGANIZE_NAME_THA), ref fORGANIZE_NAME_THA, value); }
        }
        int fORGANIZE_LEVEL;
        [Persistent(@"organize_level")]
        public int ORGANIZE_LEVEL
        {
            get { return fORGANIZE_LEVEL; }
            set { SetPropertyValue<int>(nameof(ORGANIZE_LEVEL), ref fORGANIZE_LEVEL, value); }
        }
        string fCATEGORY_NAME;
        [Size(500)]
        [Persistent(@"category_name")]
        public string CATEGORY_NAME
        {
            get { return fCATEGORY_NAME; }
            set { SetPropertyValue<string>(nameof(CATEGORY_NAME), ref fCATEGORY_NAME, value); }
        }
        string fSTATUS_NAME;
        [Size(200)]
        [Persistent(@"status_name")]
        public string STATUS_NAME
        {
            get { return fSTATUS_NAME; }
            set { SetPropertyValue<string>(nameof(STATUS_NAME), ref fSTATUS_NAME, value); }
        }
        string fFORM_IO_ID;
        [Size(24)]
        [Persistent(@"form_io_id")]
        public string FORM_IO_ID
        {
            get { return fFORM_IO_ID; }
            set { SetPropertyValue<string>(nameof(FORM_IO_ID), ref fFORM_IO_ID, value); }
        }
        string fFORM_CODE;
        [Persistent(@"form_code")]
        public string FORM_CODE
        {
            get { return fFORM_CODE; }
            set { SetPropertyValue<string>(nameof(FORM_CODE), ref fFORM_CODE, value); }
        }
        int fFLOW_SLA;
        [Persistent(@"flow_sla")]
        public int FLOW_SLA
        {
            get { return fFLOW_SLA; }
            set { SetPropertyValue<int>(nameof(FLOW_SLA), ref fFLOW_SLA, value); }
        }
        string fFLOW_UNIT;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"flow_unit")]
        public string FLOW_UNIT
        {
            get { return fFLOW_UNIT; }
            set { SetPropertyValue<string>(nameof(FLOW_UNIT), ref fFLOW_UNIT, value); }
        }
        string fFLOW_GROUP_NAME;
        [Size(500)]
        [Persistent(@"flow_group_name")]
        public string FLOW_GROUP_NAME
        {
            get { return fFLOW_GROUP_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_GROUP_NAME), ref fFLOW_GROUP_NAME, value); }
        }
        int fOFFCER_ORGANIZE_ID;
        [Persistent(@"offcer_organize_id")]
        public int OFFCER_ORGANIZE_ID
        {
            get { return fOFFCER_ORGANIZE_ID; }
            set { SetPropertyValue<int>(nameof(OFFCER_ORGANIZE_ID), ref fOFFCER_ORGANIZE_ID, value); }
        }
        string fOFFICER_FULL_NAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"officer_full_name")]
        public string OFFICER_FULL_NAME
        {
            get { return fOFFICER_FULL_NAME; }
            set { SetPropertyValue<string>(nameof(OFFICER_FULL_NAME), ref fOFFICER_FULL_NAME, value); }
        }
        string fFLOW_CODE;
        [Size(500)]
        [Persistent(@"flow_code")]
        public string FLOW_CODE
        {
            get { return fFLOW_CODE; }
            set { SetPropertyValue<string>(nameof(FLOW_CODE), ref fFLOW_CODE, value); }
        }
        string fFLOW_VERSION;
        [Size(10)]
        [Persistent(@"flow_version")]
        public string FLOW_VERSION
        {
            get { return fFLOW_VERSION; }
            set { SetPropertyValue<string>(nameof(FLOW_VERSION), ref fFLOW_VERSION, value); }
        }
        string fORG_MAIN;
        [Size(500)]
        [Persistent(@"org_main")]
        public string ORG_MAIN
        {
            get { return fORG_MAIN; }
            set { SetPropertyValue<string>(nameof(ORG_MAIN), ref fORG_MAIN, value); }
        }
        char fREJECT_FLAG;
        [Persistent(@"reject_flag")]
        public char REJECT_FLAG
        {
            get { return fREJECT_FLAG; }
            set { SetPropertyValue<char>(nameof(REJECT_FLAG), ref fREJECT_FLAG, value); }
        }
        string fREJECT_REMARK;
        [Size(2000)]
        [Persistent(@"reject_remark")]
        public string REJECT_REMARK
        {
            get { return fREJECT_REMARK; }
            set { SetPropertyValue<string>(nameof(REJECT_REMARK), ref fREJECT_REMARK, value); }
        }
        string fGROUP_STATUS_NAME;
        [Size(200)]
        [Persistent(@"group_status_name")]
        public string GROUP_STATUS_NAME
        {
            get { return fGROUP_STATUS_NAME; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_NAME), ref fGROUP_STATUS_NAME, value); }
        }
        string fGROUP_STATUS_OFFICER_NAME;
        [Size(200)]
        [Persistent(@"group_status_officer_name")]
        public string GROUP_STATUS_OFFICER_NAME
        {
            get { return fGROUP_STATUS_OFFICER_NAME; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_OFFICER_NAME), ref fGROUP_STATUS_OFFICER_NAME, value); }
        }
        string fSECTION_CODE;
        [Size(2)]
        [Persistent(@"section_code")]
        public string SECTION_CODE
        {
            get { return fSECTION_CODE; }
            set { SetPropertyValue<string>(nameof(SECTION_CODE), ref fSECTION_CODE, value); }
        }
        char fRECORD_STATUS;
        [Persistent(@"record_status")]
        public char RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<char>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        char fDEL_FLAG;
        [Persistent(@"del_flag")]
        public char DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<char>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fCREATE_DATETIME_TH;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"create_datetime_th")]
        public string CREATE_DATETIME_TH
        {
            get { return fCREATE_DATETIME_TH; }
            set { SetPropertyValue<string>(nameof(CREATE_DATETIME_TH), ref fCREATE_DATETIME_TH, value); }
        }
    }

}
