//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_count_group_status_proc_inst")]
    public partial class VIEW_COUNT_GROUP_STATUS_PROC_INST : XPLiteObject
    {
        long fROW_NUMBER;
        [Key]
        [Persistent(@"row_number")]
        public long ROW_NUMBER
        {
            get { return fROW_NUMBER; }
            set { SetPropertyValue<long>(nameof(ROW_NUMBER), ref fROW_NUMBER, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fGROUP_STATUS_CODE;
        [Size(3)]
        [Persistent(@"group_status_code")]
        public string GROUP_STATUS_CODE
        {
            get { return fGROUP_STATUS_CODE; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_CODE), ref fGROUP_STATUS_CODE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        long fCOUNT_GROUP_STATUS_CODE;
        [Persistent(@"count_group_status_code")]
        public long COUNT_GROUP_STATUS_CODE
        {
            get { return fCOUNT_GROUP_STATUS_CODE; }
            set { SetPropertyValue<long>(nameof(COUNT_GROUP_STATUS_CODE), ref fCOUNT_GROUP_STATUS_CODE, value); }
        }
    }

}
