//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_module_priv")]
    public partial class VIEW_MODULE_PRIV : XPLiteObject
    {
        int fMODULE_PRIV_ID;
        [Key]
        [Persistent(@"module_priv_id")]
        public int MODULE_PRIV_ID
        {
            get { return fMODULE_PRIV_ID; }
            set { SetPropertyValue<int>(nameof(MODULE_PRIV_ID), ref fMODULE_PRIV_ID, value); }
        }
        int fMODULE_ID;
        [Persistent(@"module_id")]
        public int MODULE_ID
        {
            get { return fMODULE_ID; }
            set { SetPropertyValue<int>(nameof(MODULE_ID), ref fMODULE_ID, value); }
        }
        int fPERMISSION_ID;
        [Persistent(@"permission_id")]
        public int PERMISSION_ID
        {
            get { return fPERMISSION_ID; }
            set { SetPropertyValue<int>(nameof(PERMISSION_ID), ref fPERMISSION_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fPERMISSION_CODE;
        [Persistent(@"permission_code")]
        public string PERMISSION_CODE
        {
            get { return fPERMISSION_CODE; }
            set { SetPropertyValue<string>(nameof(PERMISSION_CODE), ref fPERMISSION_CODE, value); }
        }
        string fPERMISSION_NAME;
        [Size(500)]
        [Persistent(@"permission_name")]
        public string PERMISSION_NAME
        {
            get { return fPERMISSION_NAME; }
            set { SetPropertyValue<string>(nameof(PERMISSION_NAME), ref fPERMISSION_NAME, value); }
        }
        string fPERMISSION_REMARK;
        [Size(5000)]
        [Persistent(@"permission_remark")]
        public string PERMISSION_REMARK
        {
            get { return fPERMISSION_REMARK; }
            set { SetPropertyValue<string>(nameof(PERMISSION_REMARK), ref fPERMISSION_REMARK, value); }
        }
        int? fAPP_ID;
        [Persistent(@"app_id")]
        public int? APP_ID
        {
            get { return fAPP_ID; }
            set { SetPropertyValue<int?>(nameof(APP_ID), ref fAPP_ID, value); }
        }
    }

}
