//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_edoc_assign")]
    public partial class VIEW_EDOC_ASSIGN : XPLiteObject
    {
        int fEDOC_ASSIGN_ID;
        [Key]
        [Persistent(@"edoc_assign_id")]
        public int EDOC_ASSIGN_ID
        {
            get { return fEDOC_ASSIGN_ID; }
            set { SetPropertyValue<int>(nameof(EDOC_ASSIGN_ID), ref fEDOC_ASSIGN_ID, value); }
        }
        int fASSIGNER_PERSONAL_ID;
        [Persistent(@"assigner_personal_id")]
        public int ASSIGNER_PERSONAL_ID
        {
            get { return fASSIGNER_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(ASSIGNER_PERSONAL_ID), ref fASSIGNER_PERSONAL_ID, value); }
        }
        int fASSIGNEE_PERSONAL_ID;
        [Persistent(@"assignee_personal_id")]
        public int ASSIGNEE_PERSONAL_ID
        {
            get { return fASSIGNEE_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(ASSIGNEE_PERSONAL_ID), ref fASSIGNEE_PERSONAL_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fDESCRIPTION;
        [Size(5000)]
        [Persistent(@"description")]
        public string DESCRIPTION
        {
            get { return fDESCRIPTION; }
            set { SetPropertyValue<string>(nameof(DESCRIPTION), ref fDESCRIPTION, value); }
        }
        string fATTACHMENT_PATH;
        [Size(5000)]
        [Persistent(@"attachment_path")]
        public string ATTACHMENT_PATH
        {
            get { return fATTACHMENT_PATH; }
            set { SetPropertyValue<string>(nameof(ATTACHMENT_PATH), ref fATTACHMENT_PATH, value); }
        }
        string fATTACHMENT_HASH;
        [Size(500)]
        [Persistent(@"attachment_hash")]
        public string ATTACHMENT_HASH
        {
            get { return fATTACHMENT_HASH; }
            set { SetPropertyValue<string>(nameof(ATTACHMENT_HASH), ref fATTACHMENT_HASH, value); }
        }
        string fEDOC_ASSIGN_SIGNATURE;
        [Size(2000)]
        [Persistent(@"edoc_assign_signature")]
        public string EDOC_ASSIGN_SIGNATURE
        {
            get { return fEDOC_ASSIGN_SIGNATURE; }
            set { SetPropertyValue<string>(nameof(EDOC_ASSIGN_SIGNATURE), ref fEDOC_ASSIGN_SIGNATURE, value); }
        }
        char fRECORD_STATUS;
        [Persistent(@"record_status")]
        public char RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<char>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        char fDEL_FLAG;
        [Persistent(@"del_flag")]
        public char DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<char>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        DateTime fSTART_DATE;
        [Persistent(@"start_date")]
        public DateTime START_DATE
        {
            get { return fSTART_DATE; }
            set { SetPropertyValue<DateTime>(nameof(START_DATE), ref fSTART_DATE, value); }
        }
        DateTime fEND_DATE;
        [Persistent(@"end_date")]
        public DateTime END_DATE
        {
            get { return fEND_DATE; }
            set { SetPropertyValue<DateTime>(nameof(END_DATE), ref fEND_DATE, value); }
        }
        string fASSIGNER_TITLE_NAME;
        [Size(200)]
        [Persistent(@"assigner_title_name")]
        public string ASSIGNER_TITLE_NAME
        {
            get { return fASSIGNER_TITLE_NAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNER_TITLE_NAME), ref fASSIGNER_TITLE_NAME, value); }
        }
        int fASSIGNER_DISTICT_ID;
        [Persistent(@"assigner_distict_id")]
        public int ASSIGNER_DISTICT_ID
        {
            get { return fASSIGNER_DISTICT_ID; }
            set { SetPropertyValue<int>(nameof(ASSIGNER_DISTICT_ID), ref fASSIGNER_DISTICT_ID, value); }
        }
        string fASSIGNER_FNAME;
        [Size(255)]
        [Persistent(@"assigner_fname")]
        public string ASSIGNER_FNAME
        {
            get { return fASSIGNER_FNAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNER_FNAME), ref fASSIGNER_FNAME, value); }
        }
        string fASSIGNER_LNAME;
        [Size(255)]
        [Persistent(@"assigner_lname")]
        public string ASSIGNER_LNAME
        {
            get { return fASSIGNER_LNAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNER_LNAME), ref fASSIGNER_LNAME, value); }
        }
        string fASSIGNEE_TITLE_NAME;
        [Size(200)]
        [Persistent(@"assignee_title_name")]
        public string ASSIGNEE_TITLE_NAME
        {
            get { return fASSIGNEE_TITLE_NAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNEE_TITLE_NAME), ref fASSIGNEE_TITLE_NAME, value); }
        }
        string fASSIGNEE_FNAME;
        [Size(255)]
        [Persistent(@"assignee_fname")]
        public string ASSIGNEE_FNAME
        {
            get { return fASSIGNEE_FNAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNEE_FNAME), ref fASSIGNEE_FNAME, value); }
        }
        string fASSIGNEE_LNAME;
        [Size(255)]
        [Persistent(@"assignee_lname")]
        public string ASSIGNEE_LNAME
        {
            get { return fASSIGNEE_LNAME; }
            set { SetPropertyValue<string>(nameof(ASSIGNEE_LNAME), ref fASSIGNEE_LNAME, value); }
        }
        string fSTATUS_NAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"status_name")]
        public string STATUS_NAME
        {
            get { return fSTATUS_NAME; }
            set { SetPropertyValue<string>(nameof(STATUS_NAME), ref fSTATUS_NAME, value); }
        }
        string fSTATUS_FLAG;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"status_flag")]
        public string STATUS_FLAG
        {
            get { return fSTATUS_FLAG; }
            set { SetPropertyValue<string>(nameof(STATUS_FLAG), ref fSTATUS_FLAG, value); }
        }
        char fCANCEL_FLAG;
        [Persistent(@"cancel_flag")]
        public char CANCEL_FLAG
        {
            get { return fCANCEL_FLAG; }
            set { SetPropertyValue<char>(nameof(CANCEL_FLAG), ref fCANCEL_FLAG, value); }
        }
        string fDESCRIPTION_CANCEL;
        [Size(5000)]
        [Persistent(@"description_cancel")]
        public string DESCRIPTION_CANCEL
        {
            get { return fDESCRIPTION_CANCEL; }
            set { SetPropertyValue<string>(nameof(DESCRIPTION_CANCEL), ref fDESCRIPTION_CANCEL, value); }
        }
    }

}
