//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_inst_tracking")]
    public partial class VIEW_PROC_INST_TRACKING : XPLiteObject
    {
        int fINST_ID;
        [Key]
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        int fORG_ID;
        [Persistent(@"org_id")]
        public int ORG_ID
        {
            get { return fORG_ID; }
            set { SetPropertyValue<int>(nameof(ORG_ID), ref fORG_ID, value); }
        }
        string fTRACKING_CODE;
        [Size(30)]
        [Persistent(@"tracking_code")]
        public string TRACKING_CODE
        {
            get { return fTRACKING_CODE; }
            set { SetPropertyValue<string>(nameof(TRACKING_CODE), ref fTRACKING_CODE, value); }
        }
        string fFORM_NAME;
        [Size(500)]
        [Persistent(@"form_name")]
        public string FORM_NAME
        {
            get { return fFORM_NAME; }
            set { SetPropertyValue<string>(nameof(FORM_NAME), ref fFORM_NAME, value); }
        }
        string fFORM_CODE;
        [Persistent(@"form_code")]
        public string FORM_CODE
        {
            get { return fFORM_CODE; }
            set { SetPropertyValue<string>(nameof(FORM_CODE), ref fFORM_CODE, value); }
        }
        string fFLOW_NAME;
        [Size(500)]
        [Persistent(@"flow_name")]
        public string FLOW_NAME
        {
            get { return fFLOW_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_NAME), ref fFLOW_NAME, value); }
        }
        string fORGANIZE_NAME_THA;
        [Size(500)]
        [Persistent(@"organize_name_tha")]
        public string ORGANIZE_NAME_THA
        {
            get { return fORGANIZE_NAME_THA; }
            set { SetPropertyValue<string>(nameof(ORGANIZE_NAME_THA), ref fORGANIZE_NAME_THA, value); }
        }
        string fPERSONAL_CITIZEN_NUMBER;
        [Size(500)]
        [Persistent(@"personal_citizen_number")]
        public string PERSONAL_CITIZEN_NUMBER
        {
            get { return fPERSONAL_CITIZEN_NUMBER; }
            set { SetPropertyValue<string>(nameof(PERSONAL_CITIZEN_NUMBER), ref fPERSONAL_CITIZEN_NUMBER, value); }
        }
        string fPERSONAL_FULL_NAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"personal_full_name")]
        public string PERSONAL_FULL_NAME
        {
            get { return fPERSONAL_FULL_NAME; }
            set { SetPropertyValue<string>(nameof(PERSONAL_FULL_NAME), ref fPERSONAL_FULL_NAME, value); }
        }
        string fSTATUS_NAME;
        [Size(200)]
        [Persistent(@"status_name")]
        public string STATUS_NAME
        {
            get { return fSTATUS_NAME; }
            set { SetPropertyValue<string>(nameof(STATUS_NAME), ref fSTATUS_NAME, value); }
        }
        string fSTATUS_CODE;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"status_code")]
        public string STATUS_CODE
        {
            get { return fSTATUS_CODE; }
            set { SetPropertyValue<string>(nameof(STATUS_CODE), ref fSTATUS_CODE, value); }
        }
        string fGROUP_STATUS_CODE;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"group_status_code")]
        public string GROUP_STATUS_CODE
        {
            get { return fGROUP_STATUS_CODE; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_CODE), ref fGROUP_STATUS_CODE, value); }
        }
        string fGROUP_STATUS_NAME;
        [Size(200)]
        [Persistent(@"group_status_name")]
        public string GROUP_STATUS_NAME
        {
            get { return fGROUP_STATUS_NAME; }
            set { SetPropertyValue<string>(nameof(GROUP_STATUS_NAME), ref fGROUP_STATUS_NAME, value); }
        }
        char fDEL_FLAG;
        [Persistent(@"del_flag")]
        public char DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<char>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fCREATE_DATE_TH;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"create_date_th")]
        public string CREATE_DATE_TH
        {
            get { return fCREATE_DATE_TH; }
            set { SetPropertyValue<string>(nameof(CREATE_DATE_TH), ref fCREATE_DATE_TH, value); }
        }
        string fUPDATE_DATE_TH;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"update_date_th")]
        public string UPDATE_DATE_TH
        {
            get { return fUPDATE_DATE_TH; }
            set { SetPropertyValue<string>(nameof(UPDATE_DATE_TH), ref fUPDATE_DATE_TH, value); }
        }
        string fDISTRICT_NAME_THA;
        [Size(500)]
        [Persistent(@"district_name_tha")]
        public string DISTRICT_NAME_THA
        {
            get { return fDISTRICT_NAME_THA; }
            set { SetPropertyValue<string>(nameof(DISTRICT_NAME_THA), ref fDISTRICT_NAME_THA, value); }
        }
        string fDISTRICT_NAME_ENG;
        [Size(500)]
        [Persistent(@"district_name_eng")]
        public string DISTRICT_NAME_ENG
        {
            get { return fDISTRICT_NAME_ENG; }
            set { SetPropertyValue<string>(nameof(DISTRICT_NAME_ENG), ref fDISTRICT_NAME_ENG, value); }
        }
    }

}
