//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_organize_province")]
    public partial class VIEW_ORGANIZE_PROVINCE : XPLiteObject
    {
        int fORGANIZE_PROVINCE_ID;
        [Key]
        [Persistent(@"organize_province_id")]
        public int ORGANIZE_PROVINCE_ID
        {
            get { return fORGANIZE_PROVINCE_ID; }
            set { SetPropertyValue<int>(nameof(ORGANIZE_PROVINCE_ID), ref fORGANIZE_PROVINCE_ID, value); }
        }
        int? fORGANIZE_ID;
        [Persistent(@"organize_id")]
        public int? ORGANIZE_ID
        {
            get { return fORGANIZE_ID; }
            set { SetPropertyValue<int?>(nameof(ORGANIZE_ID), ref fORGANIZE_ID, value); }
        }
        int? fPROVINCE_ID;
        [Persistent(@"province_id")]
        public int? PROVINCE_ID
        {
            get { return fPROVINCE_ID; }
            set { SetPropertyValue<int?>(nameof(PROVINCE_ID), ref fPROVINCE_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int? fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int? CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime? fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime? CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fPROVINCE_NAME_THA;
        [Size(500)]
        [Persistent(@"province_name_tha")]
        public string PROVINCE_NAME_THA
        {
            get { return fPROVINCE_NAME_THA; }
            set { SetPropertyValue<string>(nameof(PROVINCE_NAME_THA), ref fPROVINCE_NAME_THA, value); }
        }
        string fORGANIZE_NAME_THA;
        [Size(500)]
        [Persistent(@"organize_name_tha")]
        public string ORGANIZE_NAME_THA
        {
            get { return fORGANIZE_NAME_THA; }
            set { SetPropertyValue<string>(nameof(ORGANIZE_NAME_THA), ref fORGANIZE_NAME_THA, value); }
        }
    }

}
