//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_notification")]
    public partial class VIEW_NOTIFICATION : XPLiteObject
    {
        int fNOTIFICATION_TO_ID;
        [Key]
        [Persistent(@"notification_to_id")]
        public int NOTIFICATION_TO_ID
        {
            get { return fNOTIFICATION_TO_ID; }
            set { SetPropertyValue<int>(nameof(NOTIFICATION_TO_ID), ref fNOTIFICATION_TO_ID, value); }
        }
        int fNOTIFICATION_ID;
        [Persistent(@"notification_id")]
        public int NOTIFICATION_ID
        {
            get { return fNOTIFICATION_ID; }
            set { SetPropertyValue<int>(nameof(NOTIFICATION_ID), ref fNOTIFICATION_ID, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fFLAG_READ;
        [Persistent(@"flag_read")]
        public string FLAG_READ
        {
            get { return fFLAG_READ; }
            set { SetPropertyValue<string>(nameof(FLAG_READ), ref fFLAG_READ, value); }
        }
        DateTime? fREAD_DATE;
        [Persistent(@"read_date")]
        public DateTime? READ_DATE
        {
            get { return fREAD_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(READ_DATE), ref fREAD_DATE, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fNOTIFICATION_FROM;
        [Size(500)]
        [Persistent(@"notification_from")]
        public string NOTIFICATION_FROM
        {
            get { return fNOTIFICATION_FROM; }
            set { SetPropertyValue<string>(nameof(NOTIFICATION_FROM), ref fNOTIFICATION_FROM, value); }
        }
        int fNOTIFICATION_FROM_PERSONAL_ID;
        [Persistent(@"notification_from_personal_id")]
        public int NOTIFICATION_FROM_PERSONAL_ID
        {
            get { return fNOTIFICATION_FROM_PERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(NOTIFICATION_FROM_PERSONAL_ID), ref fNOTIFICATION_FROM_PERSONAL_ID, value); }
        }
        string fNOTIFICATION_SUBJECT;
        [Size(500)]
        [Persistent(@"notification_subject")]
        public string NOTIFICATION_SUBJECT
        {
            get { return fNOTIFICATION_SUBJECT; }
            set { SetPropertyValue<string>(nameof(NOTIFICATION_SUBJECT), ref fNOTIFICATION_SUBJECT, value); }
        }
        string fNOTIFICATION_BODY;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"notification_body")]
        public string NOTIFICATION_BODY
        {
            get { return fNOTIFICATION_BODY; }
            set { SetPropertyValue<string>(nameof(NOTIFICATION_BODY), ref fNOTIFICATION_BODY, value); }
        }
        DateTime fNOTIFICATION_DATE;
        [Persistent(@"notification_date")]
        public DateTime NOTIFICATION_DATE
        {
            get { return fNOTIFICATION_DATE; }
            set { SetPropertyValue<DateTime>(nameof(NOTIFICATION_DATE), ref fNOTIFICATION_DATE, value); }
        }
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
    }

}
