//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_inst_attachment_officer")]
    public partial class VIEW_PROC_INST_ATTACHMENT_OFFICER : XPLiteObject
    {
        int fINST_ATTACHMENT_OFFICER_ID;
        [Key]
        [Persistent(@"inst_attachment_officer_id")]
        public int INST_ATTACHMENT_OFFICER_ID
        {
            get { return fINST_ATTACHMENT_OFFICER_ID; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_OFFICER_ID), ref fINST_ATTACHMENT_OFFICER_ID, value); }
        }
        int fINST_ID;
        [Persistent(@"inst_id")]
        public int INST_ID
        {
            get { return fINST_ID; }
            set { SetPropertyValue<int>(nameof(INST_ID), ref fINST_ID, value); }
        }
        string fINST_ATTACHMENT_OFFICER_NAME;
        [Size(2000)]
        [Persistent(@"inst_attachment_officer_name")]
        public string INST_ATTACHMENT_OFFICER_NAME
        {
            get { return fINST_ATTACHMENT_OFFICER_NAME; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_OFFICER_NAME), ref fINST_ATTACHMENT_OFFICER_NAME, value); }
        }
        DateTime fINST_ATTACHMENT_OFFICER_DATE;
        [Persistent(@"inst_attachment_officer_date")]
        public DateTime INST_ATTACHMENT_OFFICER_DATE
        {
            get { return fINST_ATTACHMENT_OFFICER_DATE; }
            set { SetPropertyValue<DateTime>(nameof(INST_ATTACHMENT_OFFICER_DATE), ref fINST_ATTACHMENT_OFFICER_DATE, value); }
        }
        string fINST_ATTACHMENT_OFFICER_PATH;
        [Size(4000)]
        [Persistent(@"inst_attachment_officer_path")]
        public string INST_ATTACHMENT_OFFICER_PATH
        {
            get { return fINST_ATTACHMENT_OFFICER_PATH; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_OFFICER_PATH), ref fINST_ATTACHMENT_OFFICER_PATH, value); }
        }
        string fWF_INSTANCE_ID;
        [Size(50)]
        [Persistent(@"wf_instance_id")]
        public string WF_INSTANCE_ID
        {
            get { return fWF_INSTANCE_ID; }
            set { SetPropertyValue<string>(nameof(WF_INSTANCE_ID), ref fWF_INSTANCE_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int? fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int? UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int?>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime? fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime? UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime?>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        int fINST_ATTACHMENT_OFFICER_SIZE;
        [Persistent(@"inst_attachment_officer_size")]
        public int INST_ATTACHMENT_OFFICER_SIZE
        {
            get { return fINST_ATTACHMENT_OFFICER_SIZE; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_OFFICER_SIZE), ref fINST_ATTACHMENT_OFFICER_SIZE, value); }
        }
        int fINST_ATTACHMENT_TYPE_ID;
        [Persistent(@"inst_attachment_type_id")]
        public int INST_ATTACHMENT_TYPE_ID
        {
            get { return fINST_ATTACHMENT_TYPE_ID; }
            set { SetPropertyValue<int>(nameof(INST_ATTACHMENT_TYPE_ID), ref fINST_ATTACHMENT_TYPE_ID, value); }
        }
        char fPUBLISH_FLAG;
        [Persistent(@"publish_flag")]
        public char PUBLISH_FLAG
        {
            get { return fPUBLISH_FLAG; }
            set { SetPropertyValue<char>(nameof(PUBLISH_FLAG), ref fPUBLISH_FLAG, value); }
        }
        string fINST_ATTACHMENT_TYPE_NAME;
        [Size(2000)]
        [Persistent(@"inst_attachment_type_name")]
        public string INST_ATTACHMENT_TYPE_NAME
        {
            get { return fINST_ATTACHMENT_TYPE_NAME; }
            set { SetPropertyValue<string>(nameof(INST_ATTACHMENT_TYPE_NAME), ref fINST_ATTACHMENT_TYPE_NAME, value); }
        }
        string fOFFICER_ATTACHMENT_FLAG;
        [Persistent(@"officer_attachment_flag")]
        public string OFFICER_ATTACHMENT_FLAG
        {
            get { return fOFFICER_ATTACHMENT_FLAG; }
            set { SetPropertyValue<string>(nameof(OFFICER_ATTACHMENT_FLAG), ref fOFFICER_ATTACHMENT_FLAG, value); }
        }
        string fTRACKING_CODE;
        [Size(30)]
        [Persistent(@"tracking_code")]
        public string TRACKING_CODE
        {
            get { return fTRACKING_CODE; }
            set { SetPropertyValue<string>(nameof(TRACKING_CODE), ref fTRACKING_CODE, value); }
        }
        string fEXT1;
        [Size(255)]
        [Persistent(@"ext1")]
        public string EXT1
        {
            get { return fEXT1; }
            set { SetPropertyValue<string>(nameof(EXT1), ref fEXT1, value); }
        }
        int fPERSONAL_ID;
        [Persistent(@"personal_id")]
        public int PERSONAL_ID
        {
            get { return fPERSONAL_ID; }
            set { SetPropertyValue<int>(nameof(PERSONAL_ID), ref fPERSONAL_ID, value); }
        }
        string fSTATUS_CODE;
        [Size(3)]
        [Persistent(@"status_code")]
        public string STATUS_CODE
        {
            get { return fSTATUS_CODE; }
            set { SetPropertyValue<string>(nameof(STATUS_CODE), ref fSTATUS_CODE, value); }
        }
    }

}
