//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_proc_flow")]
    public partial class VIEW_PROC_FLOW : XPLiteObject
    {
        int fFLOW_ID;
        [Key]
        [Persistent(@"flow_id")]
        public int FLOW_ID
        {
            get { return fFLOW_ID; }
            set { SetPropertyValue<int>(nameof(FLOW_ID), ref fFLOW_ID, value); }
        }
        string fFLOW_NAME;
        [Size(500)]
        [Persistent(@"flow_name")]
        public string FLOW_NAME
        {
            get { return fFLOW_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_NAME), ref fFLOW_NAME, value); }
        }
        string fWF_DEFINITION_ID;
        [Size(500)]
        [Persistent(@"wf_definition_id")]
        public string WF_DEFINITION_ID
        {
            get { return fWF_DEFINITION_ID; }
            set { SetPropertyValue<string>(nameof(WF_DEFINITION_ID), ref fWF_DEFINITION_ID, value); }
        }
        string fRECORD_STATUS;
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fDEL_FLAG;
        [Persistent(@"del_flag")]
        public string DEL_FLAG
        {
            get { return fDEL_FLAG; }
            set { SetPropertyValue<string>(nameof(DEL_FLAG), ref fDEL_FLAG, value); }
        }
        int fCREATE_USER_ID;
        [Persistent(@"create_user_id")]
        public int CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        DateTime fCREATE_DATE;
        [Persistent(@"create_date")]
        public DateTime CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        int fUPDATE_USER_ID;
        [Persistent(@"update_user_id")]
        public int UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<int>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
        DateTime fUPDATE_DATE;
        [Persistent(@"update_date")]
        public DateTime UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<DateTime>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        int fFLOW_GROUP_ID;
        [Persistent(@"flow_group_id")]
        public int FLOW_GROUP_ID
        {
            get { return fFLOW_GROUP_ID; }
            set { SetPropertyValue<int>(nameof(FLOW_GROUP_ID), ref fFLOW_GROUP_ID, value); }
        }
        int fFLOW_SLA;
        [Persistent(@"flow_sla")]
        public int FLOW_SLA
        {
            get { return fFLOW_SLA; }
            set { SetPropertyValue<int>(nameof(FLOW_SLA), ref fFLOW_SLA, value); }
        }
        string fFLOW_UNIT;
        [Persistent(@"flow_unit")]
        public string FLOW_UNIT
        {
            get { return fFLOW_UNIT; }
            set { SetPropertyValue<string>(nameof(FLOW_UNIT), ref fFLOW_UNIT, value); }
        }
        string fFLOW_GROUP_NAME;
        [Size(500)]
        [Persistent(@"flow_group_name")]
        public string FLOW_GROUP_NAME
        {
            get { return fFLOW_GROUP_NAME; }
            set { SetPropertyValue<string>(nameof(FLOW_GROUP_NAME), ref fFLOW_GROUP_NAME, value); }
        }
        string fFLOW_CODE;
        [Size(500)]
        [Persistent(@"flow_code")]
        public string FLOW_CODE
        {
            get { return fFLOW_CODE; }
            set { SetPropertyValue<string>(nameof(FLOW_CODE), ref fFLOW_CODE, value); }
        }
        string fFLOW_VERSION;
        [Size(10)]
        [Persistent(@"flow_version")]
        public string FLOW_VERSION
        {
            get { return fFLOW_VERSION; }
            set { SetPropertyValue<string>(nameof(FLOW_VERSION), ref fFLOW_VERSION, value); }
        }
    }

}
