//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SaoTsea.Ds.Api.EntitiesCode
{

    [Persistent(@"view_sso_user_officer")]
    public partial class VIEW_SSO_USER_OFFICER : XPLiteObject
    {
        long fPK_ID;
        [Key]
        [Persistent(@"pk_id")]
        public long PK_ID
        {
            get { return fPK_ID; }
            set { SetPropertyValue<long>(nameof(PK_ID), ref fPK_ID, value); }
        }
        string fSSO_CARD_ID;
        [Size(23)]
        [Persistent(@"sso_card_id")]
        public string SSO_CARD_ID
        {
            get { return fSSO_CARD_ID; }
            set { SetPropertyValue<string>(nameof(SSO_CARD_ID), ref fSSO_CARD_ID, value); }
        }
        string fADMIN_CODE;
        [Persistent(@"admin_code")]
        public string ADMIN_CODE
        {
            get { return fADMIN_CODE; }
            set { SetPropertyValue<string>(nameof(ADMIN_CODE), ref fADMIN_CODE, value); }
        }
        string fADMIN_NAME;
        [Size(200)]
        [Persistent(@"admin_name")]
        public string ADMIN_NAME
        {
            get { return fADMIN_NAME; }
            set { SetPropertyValue<string>(nameof(ADMIN_NAME), ref fADMIN_NAME, value); }
        }
        string fSSO_PERSONAL_FULLNAME;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"sso_personal_fullname")]
        public string SSO_PERSONAL_FULLNAME
        {
            get { return fSSO_PERSONAL_FULLNAME; }
            set { SetPropertyValue<string>(nameof(SSO_PERSONAL_FULLNAME), ref fSSO_PERSONAL_FULLNAME, value); }
        }
        string fSSO_WORK_LINE_NAME;
        [Size(500)]
        [Persistent(@"sso_work_line_name")]
        public string SSO_WORK_LINE_NAME
        {
            get { return fSSO_WORK_LINE_NAME; }
            set { SetPropertyValue<string>(nameof(SSO_WORK_LINE_NAME), ref fSSO_WORK_LINE_NAME, value); }
        }
        string fWORK_LINE_CODE;
        [Size(50)]
        [Persistent(@"work_line_code")]
        public string WORK_LINE_CODE
        {
            get { return fWORK_LINE_CODE; }
            set { SetPropertyValue<string>(nameof(WORK_LINE_CODE), ref fWORK_LINE_CODE, value); }
        }
        string fSSO_ORG_CODE;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"sso_org_code")]
        public string SSO_ORG_CODE
        {
            get { return fSSO_ORG_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_ORG_CODE), ref fSSO_ORG_CODE, value); }
        }
        string fORG_NAME_TH;
        [Size(500)]
        [Persistent(@"org_name_th")]
        public string ORG_NAME_TH
        {
            get { return fORG_NAME_TH; }
            set { SetPropertyValue<string>(nameof(ORG_NAME_TH), ref fORG_NAME_TH, value); }
        }
        string fORG_NAME_DETAIL;
        [Size(5000)]
        [Persistent(@"org_name_detail")]
        public string ORG_NAME_DETAIL
        {
            get { return fORG_NAME_DETAIL; }
            set { SetPropertyValue<string>(nameof(ORG_NAME_DETAIL), ref fORG_NAME_DETAIL, value); }
        }
        int fORG_ID;
        [Persistent(@"org_id")]
        public int ORG_ID
        {
            get { return fORG_ID; }
            set { SetPropertyValue<int>(nameof(ORG_ID), ref fORG_ID, value); }
        }
        string fSSO_POSITION_ID;
        [Size(20)]
        [Persistent(@"sso_position_id")]
        public string SSO_POSITION_ID
        {
            get { return fSSO_POSITION_ID; }
            set { SetPropertyValue<string>(nameof(SSO_POSITION_ID), ref fSSO_POSITION_ID, value); }
        }
        DateTime fSSO_BIRTHDAYS;
        [Persistent(@"sso_birthdays")]
        public DateTime SSO_BIRTHDAYS
        {
            get { return fSSO_BIRTHDAYS; }
            set { SetPropertyValue<DateTime>(nameof(SSO_BIRTHDAYS), ref fSSO_BIRTHDAYS, value); }
        }
        string fSSO_TEL;
        [Size(40)]
        [Persistent(@"sso_tel")]
        public string SSO_TEL
        {
            get { return fSSO_TEL; }
            set { SetPropertyValue<string>(nameof(SSO_TEL), ref fSSO_TEL, value); }
        }
        string fSSO_WORK_LINE_CODE;
        [Size(20)]
        [Persistent(@"sso_work_line_code")]
        public string SSO_WORK_LINE_CODE
        {
            get { return fSSO_WORK_LINE_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_WORK_LINE_CODE), ref fSSO_WORK_LINE_CODE, value); }
        }
        string fSSO_DEPARTMENT_CODE;
        [Size(10)]
        [Persistent(@"sso_department_code")]
        public string SSO_DEPARTMENT_CODE
        {
            get { return fSSO_DEPARTMENT_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_DEPARTMENT_CODE), ref fSSO_DEPARTMENT_CODE, value); }
        }
        string fSSO_DIVISION_CODE;
        [Size(6)]
        [Persistent(@"sso_division_code")]
        public string SSO_DIVISION_CODE
        {
            get { return fSSO_DIVISION_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_DIVISION_CODE), ref fSSO_DIVISION_CODE, value); }
        }
        string fSSO_SECTION_CODE;
        [Size(6)]
        [Persistent(@"sso_section_code")]
        public string SSO_SECTION_CODE
        {
            get { return fSSO_SECTION_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_SECTION_CODE), ref fSSO_SECTION_CODE, value); }
        }
        string fSSO_JOB_CODE;
        [Size(6)]
        [Persistent(@"sso_job_code")]
        public string SSO_JOB_CODE
        {
            get { return fSSO_JOB_CODE; }
            set { SetPropertyValue<string>(nameof(SSO_JOB_CODE), ref fSSO_JOB_CODE, value); }
        }
        string fCREATE_DATE;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"create_date")]
        public string CREATE_DATE
        {
            get { return fCREATE_DATE; }
            set { SetPropertyValue<string>(nameof(CREATE_DATE), ref fCREATE_DATE, value); }
        }
        string fCREATE_USER_ID;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"create_user_id")]
        public string CREATE_USER_ID
        {
            get { return fCREATE_USER_ID; }
            set { SetPropertyValue<string>(nameof(CREATE_USER_ID), ref fCREATE_USER_ID, value); }
        }
        string fRECORD_STATUS;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"record_status")]
        public string RECORD_STATUS
        {
            get { return fRECORD_STATUS; }
            set { SetPropertyValue<string>(nameof(RECORD_STATUS), ref fRECORD_STATUS, value); }
        }
        string fUPDATE_DATE;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"update_date")]
        public string UPDATE_DATE
        {
            get { return fUPDATE_DATE; }
            set { SetPropertyValue<string>(nameof(UPDATE_DATE), ref fUPDATE_DATE, value); }
        }
        string fUPDATE_USER_ID;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"update_user_id")]
        public string UPDATE_USER_ID
        {
            get { return fUPDATE_USER_ID; }
            set { SetPropertyValue<string>(nameof(UPDATE_USER_ID), ref fUPDATE_USER_ID, value); }
        }
    }

}
